add 9 functions
PrismarineJS/node-vec3 pull request #1
Opened 2019-07-14 11:37 UTC by kamesa7

added
norm() // length of the vector
unit() // the vector of length 1
scale(scalar)
3 distanceTo(other)
innerProduct(other)
manhattanDistanceTo(other)
toArray()

2019-07-14 11:43 UTC, rom1504 requested changes
One small change to make, other than that it looks good to me.

2019-07-14 11:43 UTC, rom1504 commented on index.js
> +  } else {
Would be better to return a new vector here to he coherent with the other case (callers should be able to assume mutability or immutability)

2019-07-14 12:52 UTC, kamesa7 commented
Thank you for the suggestion. I fixed that point.

2019-07-14 13:06 UTC, rom1504 approved these changes
LGTM
@andrewrk can you merge ? (Maybe you could add me as maintainer for this lib too as it's mainly used in mineflayer ?)

2019-10-01 14:56 UTC, rom1504 commented
Why did you close ?

2019-10-01 21:55 UTC, andrewrk commented
I will be happy to add @rom1504 as a maintainer when I get back home

2019-10-01 21:56 UTC, merged

2019-10-02 15:34 UTC, andrewrk commented
@rom1504 you now have write access to this repository and you are an owner of the npm package.

2019-10-02 16:28 UTC, rom1504 commented
Thanks !

On Wed, Oct 2, 2019, 17:34 Andrew Kelley <notifications@github.com> wrote:

> @rom1504 <https://github.com/rom1504> you now have write access to this
> repository and you are an owner of the npm package.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andrewrk/node-vec3/pull/1?email_source=notifications&email_token=AAR437UPTD3OIRJVBDFJWZ3QMS5RBA5CNFSM4IDNQT52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAFFZSY#issuecomment-537550027>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAR437RJFM53ORZKEQ74UU3QMS5RBANCNFSM4IDNQT5Q>
> .
>